# Generated by Django 3.2.4 on 2021-06-24 09:57

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pages',
            name='slug',
        ),
        migrations.AddField(
            model_name='pages',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pages',
            name='resume',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
